type: google.api.Service
config_version: 3
name: polvo-endpoint.endpoints.aio-shopify-services.cloud.goog
title: Polvo API Endpoint

endpoints:
  - name: polvo-endpoint.aiocean.services
    allow_cors: true
apis:
  - name: aiocean.polvo.v1.PolvoService

usage:
  rules:
    - selector: aiocean.polvo.v1.PolvoService.*
      allow_unregistered_calls: true

backend:
  rules:
    - selector: "aiocean.polvo.v1.PolvoService.*"
      address: grpcs://polvo.aiocean.services
