type: google.api.Service
config_version: 3
name: polvo-endpoint.endpoints.aio-shopify-services.cloud.goog
title: Polvo API Endpoint

authentication:
  providers:
    - id: google_service_account
      issuer: polvo-endpoint-client
      jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/polvo-endpoint-client
  rules:
    - selector: "*"
      requirements:
        - provider_id: google_service_account
endpoints:
  - name: polvo-endpoint.aiocean.services
    allow_cors: true
apis:
  - name: aiocean.polvo.v1.PolvoService

usage:
  rules:
    - selector: aiocean.polvo.v1.PolvoService.*
      allow_unregistered_calls: true

backend:
  rules:
    - selector: "aiocean.polvo.v1.PolvoService.*"
      address: grpcs://polvo.aiocean.services
